---
# https://github.com/aenglund/nodejs-ansible
# File: node.yml
# Part: nodejs
#
# Description: Installs nodejs from source
#
# Parameters - Must be definied in playbook:
#   - node.path = The nodejs path
#   - node.prefix = The prefix
#   - node.tarball = The tarball filename at nodejs.org
#   - node.version = The wanted version of node to be installed

- name: Node.js | Checking installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{ node.version }}
  register: wanted_version_installed
  ignore_errors: true
  tags:
    - nodejs
    - common

- name: Node.js | Download nvm
  action: get_url
  args:
    url: https://raw.github.com/creationix/nvm/master/install.sh
    validate_certs: no
    dest: /tmp/
  when: wanted_version_installed.rc == 1
  sudo: false
  tags:
    - nodejs
    - common

- name: Node.js | Add permisions to nvm installer
  shell: chmod 777 ./install.sh
  args:
    chdir: /tmp
  when: wanted_version_installed.rc == 1
  tags:
    - nodejs
    - common

- name: Node.js | Launch nvm install script
  shell: ./install.sh
  args:
    chdir: /tmp
  when: wanted_version_installed.rc == 1
  sudo: false
  ignore_errors: yes
  tags:
    - nodejs
    - common

- name: Node.js | Create .bashrc file
  shell: touch ~/.bash_profile
  when: wanted_version_installed.rc == 1
  sudo: false
  ignore_errors: true
  tags:
    - nodejs
    - common

- name: Node.js | Load nvm
  action: lineinfile
  args:
    dest: ~/.bash_profile
    line: source ~/.nvm/nvm.sh
  when: wanted_version_installed.rc == 1
  sudo: false
  ignore_errors: yes
  tags:
    - nodejs
    - common

- name: Node.js | Install Node.JS
  shell: source ~/.nvm/nvm.sh && nvm install {{ node.version }}
  args:
    executable: /bin/bash
  when: wanted_version_installed.rc == 1
  sudo: false
  tags:
    - nodejs
    - common

- name: Node.js | Load Node.JS {{ node.version }}
  shell: source ~/.nvm/nvm.sh && nvm use {{ node.version }}
  args:
    executable: /bin/bash
  when: wanted_version_installed.rc == 1
  sudo: false
  tags:
    - nodejs
    - common

- name: Node.js | Set version to default
  shell: source ~/.nvm/nvm.sh && nvm alias default {{ node.version }}
  args:
    executable: /bin/bash
  when: wanted_version_installed.rc == 1
  sudo: false
  tags:
    - nodejs
    - common



#- name: Node.js | Fetching node.js source
#  action: get_url url=http://nodejs.org/dist/v{{ node.version }}/{{ node.tarball }} dest=/tmp/
#  when: wanted_version_installed.rc == 1
#  tags:
#    - nodejs
#    - common

#- name: Node.js | Unpack node.js tarball
#  command: tar zxf {{ node.tarball }} chdir=/tmp
#  when: wanted_version_installed.rc == 1
#  tags:
#    - nodejs
#    - common

#- name: Node.js | Configure
#  shell: /usr/bin/python ./configure --prefix={{ node.path }} chdir=/tmp/{{ node.prefix }}
#  when: wanted_version_installed.rc == 1
#  tags:
#    - nodejs
#    - common

#- name: Node.js | Make
#  shell: /usr/bin/make chdir=/tmp/{{ node.prefix }}/
#  when: wanted_version_installed.rc == 1
#  tags:
#    - nodejs
#    - common

#- name: Node.js | Make install
#  shell: /usr/bin/make install chdir=/tmp/{{ node.prefix }}/
#  when: wanted_version_installed.rc == 1
#  tags:
#    - nodejs
#    - common

- name: npm install | Install proyect dependencies
  shell: source ~/.nvm/nvm.sh && npm install
  args:
    executable: /bin/bash
    chdir: /vagrant/node
  sudo: false
  ignore_errors: true
  tags:
    - npm_install
    - common
