#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: usersList_screen
  screens: 
    usersList_screen: &usersList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Users
      title: _("List of %s %2s", ngettext('User', 'Users', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            usersEdit_screen: true
          dialogs: 
            usersDel_dialog: true
          default: usersEdit_screen
      options: 
        title: _("Options")
        screens: 
          usersNew_screen: true
        dialogs: 
          usersDel_dialog: true
    usersNew_screen: &usersNew_screenLink 
      <<: *Users
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('User', 'Users', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          createdOn: true
    usersEdit_screen: &usersEdit_screenLink 
      <<: *Users
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('User', 'Users', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          createdOn: true
  dialogs: 
    usersDel_dialog: &usersDel_dialogLink 
      <<: *Users
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('User', 'Users', 1))
      description: _("Do you want to delete this %s?", ngettext('User', 'Users', 1))
      message: _("%s successfully deleted.", ngettext('User', 'Users', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
